//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TNM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attachments
    {
        public int AttachmentId { get; set; }
        public Nullable<int> TaskId { get; set; }
        public string FilePath { get; set; }
        public string FileName { get; set; }
        public Nullable<System.DateTime> UploadedAt { get; set; }
    
        public virtual Tasks Tasks { get; set; }
    }
}
