//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TNM
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskHistory
    {
        public int HistoryId { get; set; }
        public Nullable<int> TaskId { get; set; }
        public Nullable<int> ChangedByUserId { get; set; }
        public string OldStatus { get; set; }
        public string NewStatus { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
        public string Description { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Tasks Tasks { get; set; }
    }
}
